version: '3.8'

services:
  # 1. 레디스 (데이터 저장소)
  redis:
    image: redis:alpine
    container_name: sendapp-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data  # 데이터가 저장될 로컬 폴더
    command: redis-server --appendonly yes
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge